# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8dc9700159bd3abd40a31484fa80e02fed091c8b37a5be42607f88b781fccc00fafb23862295879e947913b1dc33f55054ef92b4f3a96b9f9cacb4f72ecc8dd

test:
  secret_key_base: 3c1b1d58f9ea3afbfb7aa2a3ad9733d692908253ab40fb427d1f3fcd3f8c4eac1087f4deb46efbd569063c84f31f472a19d6e3b925a522b1ef5bef836ddd4bf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a8dc9700159bd3abd40a31484fa80e02fed091c8b37a5be42607f88b781fccc00fafb23862295879e947913b1dc33f55054ef92b4f3a96b9f9cacb4f72ecc8dd
